### ISSUE TITLE
Selection formatting with custom phpcs.xml (and without)

### ISSUE THREAD

**Issue by SamTyurenkov** [valeryan/vscode-phpsab#124]
Hi there,

Whenever I choose to format selection only, it still formats entire file. 
Do you think it is possible to implement any soon?

**Comment by jonathanbossenger** [comment]
@SamTyurenkov Let me test this in the week and get back to you.

**Comment by valeryan** [comment]
Phpcs does not support format by selection. It will do format by edited. It uses git diffs in the background. However, I removed the format by edited option from this extension a while ago by mistake. I haven't had time to add it back. 

We can't support format by selection because phpcs does not support it. The reason is that VSCode only sends the selection to phpcs and phpcs does not work without the full context of the document because it needs to tokenize the document to format it.
