### ISSUE TITLE
Should not do syntax checking outside the specified path

### ISSUE THREAD

**Issue by pattisahusiwa** [valeryan/vscode-phpsab#16]
The attached test project will demonstrate this issue. `error.php` doesn't have to be checked.

PHPCS also produce a bug

`~/test/vendor/bin/phpcs --report=json -q --standard=~/test/phpcs.xml --stdin-path=~/test/fail/error.php`

should not report any errors.

Attachment:
[test.tar.gz](https://github.com/valeryan/vscode-phpsab/files/4443044/test.tar.gz)

**Comment by valeryan** [comment]
This is The Way

https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset

```
    Note that file and directory paths specified in a ruleset are
    relative to the ruleset's location, and that specifying any file or
    directory path on the command line will ignore all file tags.
```

This is the expected behavior of phpcs and phpcbf because you are specifying a file. It overrides all file tags. To work around this behavior you have to use `exclude-pattern`. 

I would recommend you add a pattern for vendor and fail in your example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="standard">
  <description>Coding standard</description>

  <config name="testVersion" value="5.4"/>

  <arg name="colors"/>
  <arg name="parallel" value="8"/>
  <arg value="psv"/>
  <arg name="extensions" value="php"/>

  <file>./src/</file>
  <exclude-pattern>*/vendor/*</exclude-pattern>
  <exclude-pattern>*/fail/*</exclude-pattern>
  <rule ref="Generic.PHP.RequireStrictTypes"/>
</ruleset>
```
