### ISSUE TITLE
A way to format using PHPSAB ignoring the defualt VScode formatter?

### ISSUE THREAD

**Issue by ivanbrkicNRLB** [valeryan/vscode-phpsab#28]
Currently the fixer.fix command just runs the default formatter. In my case that would be Intelephense. I'd like a separate command to directly format using PHPSAB. Is this a possibility?

**Comment by pattisahusiwa** [comment]
Add this to your vscode settings
````json
"[php]": {
    "editor.defaultFormatter": "valeryanm.vscode-phpsab"
 },
"intelephense.format.enable": false,
````

**Comment by ivanbrkicNRLB** [comment]
Yes but my default formatter setting (Intelephense) is intended. I need to run both, one by one as two separate commands. Is this possible? I thought `fixer.fix` would run it's own formatter, not just be an extension for `editor.action.formatDocument`

**Comment by ivanbrkicNRLB** [comment]
Because PHPSAB ignores code outside the php brackets (HTML) and Intelephense does not. But Intelephense does not use rules from a phpcs coding standard. So the hack there would be to run two commands in sequence, which can be done using an extension like [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command). 
Consider this code:

    <?php
    if ( $var1 ) {
      if ( ! $var2 ) {
        ?>
    <div class="cla"></div>
        <?php
      }
    }

After formatting with PHPSAB I get the same result. Intelephense is aware of the HTML and would format the HTML part right, like so:

    <?php
    if ( $var1 ) {
      if ( ! $var2 ) {
        ?>
        <div class="cla"></div>
        <?php
      }
    }

**Comment by valeryan** [comment]
I would recommend to not use intelephenses formatter because it attempts to do everything with little configuration. Instead, consider using dedicated formatters with a focus on what you want to format. For example: [Format HTML in PHP](https://github.com/RiFi2k/format-html-in-php)

The limitation for only one formatter at a time is the way VSCode is set up to work and I don't know that I can get around it or would try. The fix command does not get around this because the first thing it does is check configuration to see if its the active formatter for the PHP doc type.

**Comment by ivanbrkicNRLB** [comment]
I am aware of the Format HTML in PHP plugin but the plugin does not respect PHP indentation for some reason so it's of no use for me currently. I did report an [issue](https://github.com/RiFi2k/format-html-in-php/issues/45) so we'll see how that goes. Thank you for clarifying, cheers.

**Comment by nsetyo** [comment]
I'm sorry for bumping an old issue. Actually vscode can run multiple action on save using editor.codeActionsOnSave 
If this extension have own action we can using multiple formatter like prettier for style and run phpcbf for lint
