### ISSUE TITLE
Better error handling for composer errors

### ISSUE THREAD

**Issue by jasonwilliams** [valeryan/vscode-phpsab#40]
Only been getting this recently.
Using version 0.0.11

I work in a monorepo if that helps, but it was working before.

```
[2021-01-21 11:19:52.582] [exthost] [error] [valeryanm.vscode-phpsab] provider FAILED
[2021-01-21 11:19:52.582] [exthost] [error] undefined
[2021-01-21 11:20:14.098] [exthost] [error] [valeryanm.vscode-phpsab] provider FAILED
[2021-01-21 11:20:14.098] [exthost] [error] undefined
[2021-01-21 11:20:45.100] [exthost] [error] [valeryanm.vscode-phpsab] provider FAILED
[2021-01-21 11:20:45.100] [exthost] [error] undefined
```

The issue seems to be when i supply a local path to `phpsab.executablePathCBF` if i uncomment that (so i assume it uses the global one) it works ok.

**Comment by valeryan** [comment]
Not sure what's going on here. The system will search for phpcbf path based on your composer file. If you set the path it should not search for a path. As to the provider failed stuff, it's not an error I have seen.

**Comment by Druid33** [comment]
Hi, i have the same error.
Version: 0.0.12

Interesting is, that in some project your extension works, in some not. Extension setting is same, file structure of project is same, rules are same...

When i run phpcbf or phpcs from cmd line, there are no problems.

It will be nice to see more descriptive error, when debug mode is enabled

**Comment by valeryan** [comment]
I am not able to reproduce this error on any of my projects. The error indicates that the extension is failing before it starts up properly so debugging logic is not loaded yet. I would suggest launching vscode with all extensions disabled and then adding this extension only and see if it loads. You may have conflicts in your extension that are only active on certain projects because of the type of project.

**Comment by valeryan** [comment]
I released a new version that now logs to a dedicated output channel. Maybe it will help gather some more info about what is breaking for you.

**Comment by Druid33** [comment]
Thanks, logging to dedicated output channel is usefull.

The problem was in lower php version like defined in composer.json.
I develop in docker container with php8. Php8 is one of requriments in composer.json. Phpcbf in docker run without problem.
But localy on host machine i have php7. And visual studio runs on host machine.

So, when visual studio try run phpcbf, composer check dont pass and PHP Fatal error was thrown.

In my case problem is not in extension, but in my environment settings. Removing php8 requirement from composer.json solved the problem.

thanks.

**Comment by valeryan** [comment]
Thanks for the information. That will help me see if I can make the extension handle this error more gracefully.

**Comment by nelson6e65** [comment]
Is there a way to use executables from the Docker container instead of the host machine?

I tried an .sh file with `docker exec -i rcp-laravel.test-1 vendor/bin/phpcbf $@` and `vendor/bin/sail bin phpcs` but I get this message:

> _Fixer is disable for this workspace or PHPCBF was not found for this workspace._

**Comment by valeryan** [comment]
I have not tried it out but you could check out this fork https://github.com/mtbdata711/vscode-phpsab-docker
