### ISSUE TITLE
File get empty when clicked on PHPCBF: Fix this file

### ISSUE THREAD

**Issue by faisalrehmanid** [valeryan/vscode-phpsab#57]
Hi,

I'm using windows 10 and its working fine when Environment Variable path for PHP set in advanced system settings like 'C:\xampp7.1.2\php'

**Problem I am facing:** 

If I remove environment variable path for PHP from advanced system settings and place following settings in vscode global or local settings.json than it empty the file on Fix this file function. 

   "php.validate.executablePath": "C:\\xampp7.1.2\\php\\php.exe",
   "php.executablePath": "C:\\xampp7.1.2\\php\\php.exe"

Ideally it should use that php executable path or have settings like `phpsab.executablePathPHP` so it can be set locally.

Thanks!
Faisal Rehman

**Comment by valeryan** [comment]
I pushed out a quick fix that I think will address this issue. Let me know if it helps.

**Comment by yCodeTech** [comment]
I've found that, if you change location of the PHP, and change it's environment path to reflect it's new location, but forget to restart vscode, then this bug comes back into play. The file is emptied upon saving while "fixing". Once vscode is restarted, this bug stops.

So, the extension should catch when it can't find the PHP installed, and stop any PHPCBF processing, so that the file doesn't get emptied. A warning notice should appear to the user when such thing happens too.
