### ISSUE TITLE
Predefined variables produce error in phpsab.standard settings 

### ISSUE THREAD

**Issue by MannyAdumbire** [valeryan/vscode-phpsab#65]
I'm one step away from configuring this neat extension to work with my current development setup.
It works well if installed standards are mentioned by name or when trying to use a phpcs config file as the standard:
i.e.    `"phpsab.standard": "./phpcs.xml"` in VSCode settings.json

However, using predefined variables like `"phpsab.standard": "${workspaceFolder}/phpcs.xml"` produces the error below:

_ERROR: the "${workspaceFolder}/phpcs.xml" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz, Zend_

I confirmed that the reference `${workspaceFolder}/phpcs.xml ` works with other extensions.
Is this known issue or am I doing something wrong?
Thanks for any help!

**Comment by valeryan** [comment]
This is probably because my extension is using the  value as a string and not doing any interpretation of variables. 

But I am trying to decide what to do with this project, I moved on to a dotnet job and I don't currently have any Php projects to even test with. 
https://github.com/valeryan/vscode-phpsab#maintenance-status

**Comment by MannyAdumbire** [comment]
This may have just been user error or something changed between when I first tried and VSCode 1.71.2.
Either way ${fileWorkspaceFolder} is working when used like:
...
`"phpsab.standard": "${fileWorkspaceFolder}/phpcs.xml",`
...

Thanks again!
