### ISSUE TITLE
Deleting executable paths doesn't properly unset them

### ISSUE THREAD

**Issue by SeanMcMillan** [valeryan/vscode-phpsab#90]
I'm working on a project that just moved from everyone doing it their own way to having a proper composer and phpcs as part of the project. To use the project local configuration, I deleted the executable paths to my global installation of phpcs.

Unfortunately, the extension didn't pick up the project local installation. That's because deleting the paths in the setting GUI leaves
```
"phpsab.executablePathCS": ""
"phpsab.executablePathCBF: ""
```

in `settings.json`. Deleting those lines makes the extension work correctly again.

Can you adjust the extension logic to treat blank paths the same as never having set a path?

**Comment by valeryan** [comment]
Probably because I am only doing a null check to resolve the paths:

https://github.com/valeryan/vscode-phpsab/blob/427dfd0013861427474b5283a530a2931e4e3c2d/src/configuration.ts#L109
https://github.com/valeryan/vscode-phpsab/blob/427dfd0013861427474b5283a530a2931e4e3c2d/src/configuration.ts#L131

Feel free to do a PR to add an or empty to these if checks.
